const types = {
  GET_ALL_EXAMS: 'GET_ALL_EXAMS',
  GET_ALL_EXAMS_SUCCESS: 'GET_ALL_EXAMS_SUCCESS',
  GET_ALL_EXAMS_FAILED: 'GET_ALL_EXAMS_FAILED',

  GET_EXAM_BY_ID: 'GET_EXAM_BY_ID',
  GET_EXAM_BY_ID_SUCCESS: 'GET_EXAM_BY_ID_SUCCESS',
  GET_EXAM_BY_ID_FAILED: 'GET_EXAM_BY_ID_FAILED',

  CREATE_EXAM: 'CREATE_EXAM',
  CREATE_EXAM_SUCCESS: 'CREATE_EXAM_SUCCESS',
  CREATE_EXAM_FAILED: 'CREATE_EXAM_FAILED',

  CREATE_RANDOM_EXAM: 'CREATE_RANDOM_EXAM',
  CREATE_RANDOM_EXAM_SUCCESS: 'CREATE_RANDOM_EXAM_SUCCESS',
  CREATE_RANDOM_EXAM_FAILED: 'CREATE_RANDOM_EXAM_FAILED',

  UPDATE_EXAM: 'UPDATE_EXAM',
  UPDATE_EXAM_SUCCESS: 'UPDATE_EXAM_SUCCESS',
  UPDATE_EXAM_FAILED: 'UPDATE_EXAM_FAILED',

  DELETE_EXAM: 'DELETE_EXAM',
  DELETE_EXAM_SUCCESS: 'DELETE_EXAM_SUCCESS',
  DELETE_EXAM_FAILED: 'DELETE_EXAM_FAILED',
};

export default types;
