const types = {
  GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
  GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
  GET_ALL_CATEGORY_FAILED: 'GET_ALL_CATEGORY_FAILED',

  CREATE_CATEGORY: 'CREATE_CATEGORY',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILED: 'CREATE_CATEGORY_FAILED',

  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILED: 'UPDATE_CATEGORY_FAILED',

  DELETE_CATEGORY: 'DELETE_CATEGORY',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILED: 'DELETE_CATEGORY_FAILED',
};

export default types;
