const types = {
  GET_ALL_QUESTIONS: 'GET_ALL_QUESTIONS',
  GET_ALL_QUESTIONS_SUCCESS: 'GET_ALL_QUESTIONS_SUCCESS',
  GET_ALL_QUESTIONS_FAILED: 'GET_ALL_QUESTIONS_FAILED',

  CREATE_QUESTION: 'CREATE_QUESTION',
  CREATE_QUESTION_SUCCESS: 'CREATE_QUESTION_SUCCESS',
  CREATE_QUESTION_FAILED: 'CREATE_QUESTION_FAILED',

  UPDATE_QUESTION: 'UPDATE_QUESTION',
  UPDATE_QUESTION_SUCCESS: 'UPDATE_QUESTION_SUCCESS',
  UPDATE_QUESTION_FAILED: 'UPDATE_QUESTION_FAILED',

  DELETE_QUESTION: 'DELETE_QUESTION',
  DELETE_QUESTION_SUCCESS: 'DELETE_QUESTION_SUCCESS',
  DELETE_QUESTION_FAILED: 'DELETE_QUESTION_FAILED',
};

export default types;
