const types = {
  GET_ALL_ASSIGNMENTS: 'GET_ALL_ASSIGNMENTS',
  GET_ALL_ASSIGNMENTS_SUCCESS: 'GET_ALL_ASSIGNMENTS_SUCCESS',
  GET_ALL_ASSIGNMENTS_FAILED: 'GET_ALL_ASSIGNMENTS_FAILED',

  GET_ALL_ASSIGNMENT_BY_USER_ID: 'GET_ALL_ASSIGNMENT_BY_USER_ID',
  GET_ALL_ASSIGNMENT_BY_USER_ID_SUCCESS: 'GET_ALL_ASSIGNMENT_BY_USER_ID_SUCCESS',
  GET_ALL_ASSIGNMENT_BY_USER_ID_FAILED: 'GET_ALL_ASSIGNMENT_BY_USER_ID_FAILED',

  CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
  CREATE_ASSIGNMENT_SUCCESS: 'CREATE_ASSIGNMENT_SUCCESS',
  CREATE_ASSIGNMENT_FAILED: 'CREATE_ASSIGNMENT_FAILED',

  UPDATE_ASSIGNMENT: 'UPDATE_ASSIGNMENT',
  UPDATE_ASSIGNMENT_SUCCESS: 'UPDATE_ASSIGNMENT_SUCCESS',
  UPDATE_ASSIGNMENT_FAILED: 'UPDATE_ASSIGNMENT_FAILED',

  DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',
  DELETE_ASSIGNMENT_SUCCESS: 'DELETE_ASSIGNMENT_SUCCESS',
  DELETE_ASSIGNMENT_FAILED: 'DELETE_ASSIGNMENT_FAILED',
};

export default types;
