const types = {
  GET_ALL_CLASSES: 'GET_ALL_CLASSES',
  GET_ALL_CLASSES_SUCCESS: 'GET_ALL_CLASSES_SUCCESS',
  GET_ALL_CLASSES_FAILED: 'GET_ALL_CLASSES_FAILED',

  CREATE_CLASS: 'CREATE_CLASS',
  CREATE_CLASS_SUCCESS: 'CREATE_CLASS_SUCCESS',
  CREATE_CLASS_FAILED: 'CREATE_CLASS_FAILED',

  UPDATE_CLASS: 'UPDATE_CLASS',
  UPDATE_CLASS_SUCCESS: 'UPDATE_CLASS_SUCCESS',
  UPDATE_CLASS_FAILED: 'UPDATE_CLASS_FAILED',

  DELETE_CLASS: 'DELETE_CLASS',
  DELETE_CLASS_SUCCESS: 'DELETE_CLASS_SUCCESS',
  DELETE_CLASS_FAILED: 'DELETE_CLASS_FAILED',
};

export default types;
